services:
  video-trainer:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ../dataset:/dataset:ro
      - .:/app
