[tool.poetry]
name = "video-trainer"
version = "0.1.0"
description = ""
authors = ["Alexandros Vythoulkas <alvythoulkas@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
torch = "^1.11.0"
torchvision = "^0.12.0"
numpy = "^1.22.3"
opencv-python = "^4.5.5"
av = "^9.0.1"
Pillow = "^9.0.1"
tqdm = "^4.63.0"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.1.0"
pre-commit = "^2.17.0"
rope = "^0.23.0"
mypy = "^0.940"
pylint = "^2.12.2"
flake8 = "^4.0.1"
autoflake = "^1.4"
pyupgrade = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
line_length=99
profile = "black"

[tool.black]
line-length = 99
skip-string-normalization = 1

[tool.mypy]
strict = true
disallow_subclassing_any = false
