import os

DATASET_PATH = os.path.join('..', 'dataset')
TEMP_DIR = 'tmp'

FRAMES_RGB_TEMPLATE = 'frame_{0:06d}.jpg'

VIDEO_DURATION_IN_SECONDS = 300
FPS = 25

SAMPLE_DURATION_IN_FRAMES = 32
NUM_SEGMENTS = 16
FRAMES_PER_SEGMENT = 1

IMAGE_RESIZE_SIZE = (35, 35)
IMAGE_CROP_SIZE = (32, 32)

BATCH_SIZE = 32

EPOCHS = 30

LEARNING_RATE = 1e-4
